apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker-amq
spec:
  console:
    expose: true
  acceptors:
    - name: artemis
      port: 61616
      protocols: 'amqp,openwire,core'
      supportAdvisory: false
      suppressInternalManagementObjects: false
      expose: true
  adminPassword: redhat
  brokerProperties:
    - metricsConfiguration.jvmGc=true
    - metricsConfiguration.jvmThread=true
    - addressConfigurations.SHIPMENTS.routingTypes=ANYCAST
    - addressConfigurations.SHIPMENTS.queueConfigs.SHIPMENTS.address=SHIPMENTS
    - addressConfigurations.SHIPMENTS.queueConfigs.SHIPMENTS.routingType=ANYCAST
    - addressConfigurations.TAXES.routingTypes=MULTICAST
    - addressConfigurations.TAXES.queueConfigs.TAXES.address=TAXES
    - addressConfigurations.TAXES.queueConfigs.TAXES.routingType=MULTICAST
  env:
    - name: JAVA_ARGS_APPEND
      value: '-XX:MaxRAMPercentage=50'
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: true
    podSecurity: {}
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    journalType: nio
    enableMetricsPlugin: true
    storage:
      size: 5Gi
  addressSettings: {}
  version: '7.13'
  adminUser: admin
